/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jorge' at '6/14/16 8:26 PM' with Gradle 2.11
 *
 * @author jorge, @date 6/14/16 8:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
